//
//  GistsCleanSwiftRouter.swift
//  Gists
//
//  Created by Дмитрий Подольский on 05.05.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol GistsCleanSwiftRoutingLogic {
    func routeToGistDetail(with gist: GistsRoot)
}

class GistsCleanSwiftRouter: GistsCleanSwiftRoutingLogic {
    weak var viewController: UIViewController?

    func routeToGistDetail(with gist: GistsRoot) {
        let gistVC = GistViewController()
        gistVC.login = gist.owner.login ?? ""
        gistVC.gistName = gist.files.randomId?.filename ?? ""
        gistVC.avatar = gist.owner.avatar_url ?? " "
        gistVC.gistShow = gist.files.randomId?.raw_url ?? ""
        self.viewController?.navigationController?.pushViewController(gistVC, animated: true)
    }
}
