//
//  GistsCleanSwiftPresenter.swift
//  Gists
//
//  Created by Дмитрий Подольский on 05.05.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol GistsCleanSwiftPresentationLogic {
    func presentGists(_ gists: [GistsRoot])
}

class GistsCleanSwiftPresenter: GistsCleanSwiftPresentationLogic {
    weak var viewController: GistsCleanSwiftViewController?

       func presentGists(_ gists: [GistsRoot]) {
           viewController?.displayGists(gists)
       }
    }


