//
//  GistsCleanSwiftModels.swift
//  Gists
//
//  Created by Дмитрий Подольский on 05.05.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import Foundation

struct GistsRoot: Decodable {
    let owner: Owner
    let files: UnkownName
}

struct UnkownName: Decodable {
    var randomId: RandomID?
    struct RandomID: Decodable {
        let raw_url: String?
        let filename: String?
        
    }
    init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        for key in container.allKeys {
            randomId = try? container.decode(RandomID.self, forKey: key)
        }
        print(container.allKeys)
    }
    struct CodingKeys: CodingKey {
        var stringValue: String
        init?(stringValue: String) {
            self.stringValue = stringValue
        }
        var intValue: Int?
        init?(intValue: Int) {
            return nil
        }
    }
}


struct Owner: Codable {
    let login: String?
    let avatar_url: String?
}

