//
//  GistsCleanSwiftInteractor.swift
//  Gists
//
//  Created by Дмитрий Подольский on 05.05.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol GistsCleanSwiftBusinessLogic {
    func fetchData()
}
//
//protocol GistsCleanSwiftDataStore {
//    //var name: String { get set }
//}

@MainActor
class GistsCleanSwiftInteractor: GistsCleanSwiftBusinessLogic {
    var presenter: GistsCleanSwiftPresentationLogic?
   
    let baseUrl = URL(string: "https://api.github.com")!
    let path = "/gists"
    var gistsRoot = [GistsRoot]()
   
  
    func fetchData() {
        
        let networkClient = NetworkClient(baseUrl: baseUrl)
        
        Task { @MainActor in
            do {
                let data: [GistsRoot] = try await networkClient.makeRequest(path: path, responseType: [GistsRoot].self)!
                presenter?.presentGists(data)
            } catch {
                print(error)
            }
        }
    }
}
